### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by parthrawat97** [seth814/Instrument-Classifier#1]
hey seth ! This is a great program and congratulations for that.
the problem i'm facing is when i try to add my own data set in wavfiles and instruments.csv and when i run it i'm getting the following error:
ValueError: could not broadcast input array from shape (4410,2) into shape (4410).
can you help me with it.

**Comment by seth814** [comment]
Hmm if you are running this on other data then there could be some issues. Especially when creating a tkinter app. This error happens because your audio is probably stereo so it has two channels. You should convert it to mono. Not sure what line this is happening on, but conversion to mono is as simple as summing the channels and dividing by 2.

rate, signal = wavfile.read(<path to some wav file>)
mono = signal.sum(axis=1) / 2

So you would use mono as your signal. I have no idea if this will work out of the box for new data. One place that could be problematic would be line 145 of audio_eda where the signal envelope is created. You might actually end up removing all the signal if that threshold is too high.

**Comment by parthrawat97** [comment]
thank you so much ! 
i did check the audio files and it is mono. though i'll still try to do that.
Is there anything else that i can do ?

**Comment by seth814** [comment]
What line is the error occurring?

**Comment by parthrawat97** [comment]
WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
Traceback (most recent call last):
  File "model.py", line 161, in <module>
    X, y = build_1d(config)
  File "model.py", line 79, in build_1d
    X, y = np.array(X), np.array(y)
ValueError: could not broadcast input array from shape (4410,2) into shape (4410)
this is the error i am getting when I run model.py 
And when i run audio_eda.py I'm getting the following error :

 File "audio_eda.py", line 149, in <module>
    mask = envelope(signal, rate, 20)
  File "audio_eda.py", line 81, in envelope
    y = pd.Series(y).apply(np.abs)
  File "/home/icrs/PycharmProjects/lol/venv/lib/python3.5/site-packages/pandas/core/series.py", line 262, in __init__
    raise_cast_failure=True)
  File "/home/icrs/PycharmProjects/lol/venv/lib/python3.5/site-packages/pandas/core/internals/construction.py", line 658, in sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional

**Comment by seth814** [comment]
Both those errors suggest you are using two channel audio. Should go away if you convert to mono in the correct places.

**Comment by parthrawat97** [comment]
Thank you so much ! I did change it I'm still facing some errors though I'll try to solve them. But that problem is solved. :)

**Comment by parthrawat97** [comment]
hey ca you please explain how does app.py fetch the audio when we press the button.
as of now with the changed data set it is showing the labels on the button but when i press them the audio is not being played.

**Comment by seth814** [comment]
It looks like a filename is passed to the Audio class, which plays audio on a separate thread. This thread steps through the data every 10th of a second via a queue which holds 4 "steps" of data for a 4/10 second window. There is probably a better way to go about this with multiprocessing instead of multi threading... not sure

This isn't related to this issue, so I will remove the comments in a couple days. You can email me: seth8141@gmail.com if you have questions.

**Comment by parthrawat97** [comment]
alright !! thanks a ton !
